/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salescalculator;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author dashcodes
 */
// Main GUI
public class SalesCalculatorUI extends javax.swing.JFrame {
 
    
    public SalesCalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesCalculator = new javax.swing.JPanel();
        inputPane = new javax.swing.JPanel();
        phonesLabel = new javax.swing.JLabel();
        repairLabel = new javax.swing.JLabel();
        phonesFld = new javax.swing.JTextField();
        repairFld = new javax.swing.JTextField();
        resultPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultFld = new javax.swing.JTextArea();
        buttonsPane = new javax.swing.JPanel();
        calculateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Calculator");
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));

        salesCalculator.setBackground(new java.awt.Color(255, 255, 255));
        salesCalculator.setMaximumSize(new java.awt.Dimension(400, 350));
        salesCalculator.setMinimumSize(new java.awt.Dimension(400, 350));
        salesCalculator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputPane.setBackground(new java.awt.Color(204, 204, 204));

        phonesLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        phonesLabel.setText("Quantity of Phones Sold:");

        repairLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        repairLabel.setText("Number of Repair Services:");

        phonesFld.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        repairFld.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        javax.swing.GroupLayout inputPaneLayout = new javax.swing.GroupLayout(inputPane);
        inputPane.setLayout(inputPaneLayout);
        inputPaneLayout.setHorizontalGroup(
            inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inputPaneLayout.createSequentialGroup()
                        .addComponent(repairLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(repairFld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPaneLayout.createSequentialGroup()
                        .addComponent(phonesLabel)
                        .addGap(49, 49, 49)
                        .addComponent(phonesFld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        inputPaneLayout.setVerticalGroup(
            inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPaneLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonesLabel)
                    .addComponent(phonesFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repairLabel)
                    .addComponent(repairFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        salesCalculator.add(inputPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        resultPane.setBackground(new java.awt.Color(204, 204, 204));

        resultFld.setColumns(20);
        resultFld.setRows(5);
        jScrollPane1.setViewportView(resultFld);

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        salesCalculator.add(resultPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, 120));

        buttonsPane.setBackground(new java.awt.Color(204, 204, 204));

        calculateBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPaneLayout = new javax.swing.GroupLayout(buttonsPane);
        buttonsPane.setLayout(buttonsPaneLayout);
        buttonsPaneLayout.setHorizontalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(calculateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addGap(65, 65, 65))
        );
        buttonsPaneLayout.setVerticalGroup(
            buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPaneLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(buttonsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateBtn)
                    .addComponent(clearBtn))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        salesCalculator.add(buttonsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
         try {
        // Get input values
        int phonesSold = Integer.parseInt(phonesFld.getText());
        int repairServices = Integer.parseInt(repairFld.getText());

        // Constants for prices
        double phonePrice = 500.0; // Price for a phone
        double repairPricePerHour = 50.0; // Price per repair service

        // Calculate total sales
        double totalPhoneSales = phonesSold * phonePrice;
        double totalRepairSales = repairServices * repairPricePerHour;

        // Calculate total amount
        double totalAmount = totalPhoneSales + totalRepairSales;

         // If both sales are zero
        if (phonesSold == 0 && repairServices == 0) {
            resultFld.setText("No sales for the day.");
        } else {
            // Creating decimal format instance for formatting
            DecimalFormat df = new DecimalFormat("#,##0.00");
            
            // Display results
            resultFld.setText(String.format(
                    "Total Sales:\nPhones: ₱%s\nRepair Services: ₱%s\nTotal Amount: ₱%s",
                    df.format(totalPhoneSales),
                    df.format(totalRepairSales),
                    df.format(totalAmount)
                )
            );
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calculateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        resultFld.setText("");
        phonesFld.setText("");
        repairFld.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesCalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPane;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel inputPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phonesFld;
    private javax.swing.JLabel phonesLabel;
    private javax.swing.JTextField repairFld;
    private javax.swing.JLabel repairLabel;
    private javax.swing.JTextArea resultFld;
    private javax.swing.JPanel resultPane;
    private javax.swing.JPanel salesCalculator;
    // End of variables declaration//GEN-END:variables
}
